<?php

namespace Tui\DirectorsBundle\Repositories;

use Doctrine\ORM\EntityRepository;
use Tui\DirectorsBundle\Entity\Appointee;

/**
 * AppointeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointeeRepository extends EntityRepository
{
  
    public function countAppointments(Appointee $appointee)
    {
        $qc = $this->_em->createQuery("SELECT COUNT(a.companyId) FROM TuiDirectorsBundle:CompanyAppointment a WHERE a.appointeeId = :appointee");
        $qc->setParameter('appointee', $appointee->getId());
        return array_shift($qc->getSingleResult());
    }
 

    public function getAppointments(Appointee $appointee, $limit = 100, $offset = 0)
    {
      $qb = $this->_em->createQueryBuilder();
      
      $qb->add('select', 'a')
        ->add('from', 'TuiDirectorsBundle:CompanyAppointment a')
        ->add('where', 'a.appointeeId = :appointee')
        ->add('orderBy', 'a.appointedOn DESC')
        ->setParameter('appointee', $appointee->getId())
        ->setFirstResult( $offset )
        ->setMaxResults( $limit );
      
      return $qb->getQuery()->getResult();
    }
 
 
}